//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSenDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChi
    {
        public int IDDiaChi { get; set; }
        public int IDKhachHang { get; set; }
        public string DiaChi1 { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
