//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSenDa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DanhGia = new HashSet<DanhGia>();
            this.DiaChi = new HashSet<DiaChi>();
            this.DonHang = new HashSet<DonHang>();

            AnhDaiDien = "~/Content/img/add-user-icon-design-blank-avatar-placeholder-vector-34269036-removebg-preview.png";
        }
    
        public int IDKhachHang { get; set; }
        public int IDLoaiTaiKhoan { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Tên tài khoản không được để trống!")]
        public string TenTaiKhoan { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Mật khẩu không được để trống!")]
        public string MatKhau { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Tên khách hàng không được để trống!")]
        public string TenKhachHang { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Số điện thoại không được để trống!")]
        public string SoDienThoai { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Chứng minh không được để trống!")]
        public string CMND { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Email không được để trống!")]
        public string Email { get; set; }
        [NotMapped]
        public Nullable<int> DiemTichLuy { get; set; }
        [NotMapped]
        public string AnhDaiDien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaChi> DiaChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHang { get; set; }
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
        [NotMapped]
        //[Required(ErrorMessage = "Hãy chọn hình")]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
