//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSenDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int IDNhanVien { get; set; }
        public int IDLoaiTaiKhoan { get; set; }
        public int IDQuyen { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string TenNhanVien { get; set; }
        public string SoDienThoai { get; set; }
        public string CMND { get; set; }
        public string Email { get; set; }
        public string AnhDaiDien { get; set; }
    
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
