//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSenDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.DanhGia = new HashSet<DanhGia>();
            this.NhapKho = new HashSet<NhapKho>();
        }
    
        public int IDSanPham { get; set; }
        public int IDLoaiSanPham { get; set; }
        public Nullable<int> IDLoaiSenDa { get; set; }
        public Nullable<int> IDLoaiChauCay { get; set; }
        public Nullable<int> IDLoaiGiaThe { get; set; }
        public Nullable<int> IDKhuyenMai { get; set; }
        public string TenSanPham { get; set; }
        public string Hinh { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGia { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual LoaiChauCay LoaiChauCay { get; set; }
        public virtual LoaiGiaThe LoaiGiaThe { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual LoaiSenDa LoaiSenDa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapKho> NhapKho { get; set; }
    }
}
